tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'thoughtbot/formulae'
tap 'brewsci/science'
brew 'bfg'
brew 'duti'
brew 'fdupes'
brew 'fish'
brew 'nnn'
brew 'git'
brew 'grep', args: ['with-default-names']
brew 'cmake'
brew 'vim', args: ['with-lua', 'with-override-system-vi']
brew 'git-lfs'
brew 'doxygen'
brew 'hdf5'
brew 'graphviz'
brew 'hub'
brew 'sshfs'
brew 'colordiff'
brew 'wdiff'
brew 'ghostscript'
brew 'jq'
brew 'cppcheck'
brew 'cppunit'
brew 'brewsci/science/cmdstan'
brew 'mackup'
brew 'gpg'
brew 'tig'
brew 'lcov'
brew 'poppler'
brew 'sundials', args: ['without-mpi']
brew 'mas'
brew 'nmap'
brew 'eigen'
brew 'languagetool'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'pandoc-crossref'
brew 'par2'
brew 'python3', args: ['without-gdbm', 'without-readline', 'without-sqlite', 'without-xz']
brew 'ssh-copy-id'
brew 'thoughtbot/formulae/rcm'
brew 'tmux'
cask 'arq'
cask 'bibdesk'
cask 'findings'
cask 'grandperspective'
cask 'java'
cask 'nteract'
cask 'zotero'
cask 'sublime-merge'
cask 'omnifocus'
cask 'dropbox'
cask 'osxfuse'
cask 'emacs'
cask 'dash'
cask 'omniplan'
cask 'box-edit'
cask 'box-sync'
cask 'skype'
cask 'slack'
cask 'sublime-text'
cask 'texpad'
mas '1Password', id: 1333542190
mas 'AdBlock', id: 1402042596
mas 'Day One', id: 1055511498
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'XCode', id: 497799835
